spring.application.name=sistema-bancario-api

server.port=8080

# H2 Database
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:bancodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=jwt.secret=change-this-secret-key-for-demo-only-please-replace
jwt.issuer=BancoAPI
jwt.expiration=3600000
